export const albanianCountryNames: Record<string, string> = {
  AD: "Andora",
  AE: "Emiratet e Bashkuara Arabe",
  AF: "Afganistani",
  AG: "Antigua and Barbuda",
  AI: "Anguila",
  AL: "Shqipëria",
  AM: "Armenia",
  AN: "Antilet e Holandës",
  AO: "Angola",
  AQ: "Antarktika",
  AR: "Argjentina",
  AS: "Samoa Amerikane",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AZ: "Azerbajxhani",
  BA: "Bosna dhe Hercegovina",
  BB: "Barbadosi",
  BD: "Bangladeshi",
  BE: "Belgjika",
  BF: "Burkina Faso",
  BG: "Bullgaria",
  BH: "Bahraini",
  BI: "Burundi",
  BJ: "Benini",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BR: "Brazili",
  BS: "Bahamet",
  BT: "Butani",
  BV: "Ishulli Bouvet",
  BW: "Botsuana",
  BY: "Belarusia",
  BZ: "Belize",
  CA: "Kanada",
  CC: "Ishujt Kokos",
  CD: "Republika Demokratike e Kongos",
  CF: "Republika Qendrore Afrikane",
  CG: "Kongo",
  CH: "Zvicra",
  CI: "Bregu i Fildishtë",
  CK: "Ishujt Kuk",
  CL: "Kili",
  CM: "Kameruni",
  CN: "Kina",
  CO: "Kolombia",
  CR: "Kostarika",
  CU: "Kuba",
  CV: "Kepi i Gjelbër",
  CX: "Ishulli i Krishtlindjes",
  CY: "Qipro",
  CZ: "Çekia",
  DE: "Gjermania",
  DJ: "Xhibuti",
  DK: "Danimarka",
  DM: "Dominika",
  DO: "Republika Dominikane",
  DZ: "Algjeria",
  EC: "Ekuadori",
  EE: "Estonia",
  EG: "Egjipti",
  EH: "Sahara Perendimore",
  ER: "Eritrea",
  ES: "Spanja",
  ET: "Etiopia",
  FI: "Finlanda",
  FJ: "Fixhi",
  FK: "Ishujt Falkland",
  FM: "Mikronezia",
  FO: "Ishujt Faroe",
  FR: "Franca",
  GA: "Gaboni",
  GB: "Mbretëria e Bashkuar",
  GD: "Grenada",
  GE: "Gjorgjia",
  GF: "Guajana Franceze",
  GG: "Guernsei",
  GH: "Gana",
  GI: "Gjibraltari",
  GL: "Grenlanda",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadalup",
  GQ: "Guinea Ekuatoriale",
  GR: "Greqia",
  GS: "Xhorxhia Jugore dhe Ishujt Jugorë Sanduiç",
  GT: "Guatemala",
  GU: "Guami",
  GW: "Guinea-Bisau",
  GY: "Guajana",
  GZ: "Rripi i Gazës",
  HK: "Hong Kongu",
  HM: "Ishulli Heard dhe Ishujt Mekdonald",
  HN: "Hondurasi",
  HR: "Kroacia",
  HT: "Haiti",
  HU: "Hungaria",
  ID: "Indonezia",
  IE: "Irlanda",
  IL: "Izraeli",
  IM: "Ishulli Man",
  IN: "India",
  IO: "Territori Britanik i Oqeanit Indian",
  IQ: "Iraku",
  IR: "Irani",
  IS: "Islanda",
  IT: "Italia",
  JE: "Xhersei",
  JM: "Xhamaika",
  JO: "Jordani",
  JP: "Japonia",
  KE: "Kenia",
  KG: "Kirgistani",
  KH: "Kamboxha",
  KI: "Kiribati",
  KM: "Komoret",
  KN: "Saint Kitts dhe Nevis",
  KP: "Korea Veriore",
  KR: "Korea Jugore",
  KW: "Kuvajti",
  KY: "Ishujt Kajman",
  KZ: "Kazakistani",
  LA: "Laosi",
  LB: "Libani",
  LC: "Shën Lucia",
  LI: "Lihtenshtajni",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesoto",
  LT: "Lituania",
  LU: "Luksemburgu",
  LV: "Letonia",
  LY: "Libia",
  MA: "Maroko",
  MC: "Monako",
  MD: "Moldavia",
  ME: "Mali i Zi",
  MG: "Madagaskari",
  MH: "Ishujt Marshall",
  MK: "Maqedonia",
  ML: "Mali",
  MM: "Mjanmari",
  MN: "Mongolia",
  MO: "Makau",
  MP: "Ishujt e Marianas Veriore",
  MQ: "Martiniku",
  MR: "Mauritania",
  MS: "Monserati",
  MT: "Malta",
  MU: "Mauriciusi",
  MV: "Maldivet",
  MW: "Malavi",
  MX: "Meksika",
  MY: "Malezia",
  MZ: "Mozambiku",
  NA: "Namibia",
  NC: "Kaledonia e Re",
  NE: "Nigeri",
  NF: "Ishulli Norfolk",
  NG: "Nigeria",
  NI: "Nikaragua",
  NL: "Holanda",
  NO: "Norvegjia",
  NP: "Nepali",
  NR: "Nauru",
  NU: "Niue",
  NZ: "Zelanda e Re",
  OM: "Omani",
  PA: "Panama",
  PE: "Peru",
  PF: "Polinezia Franceze",
  PG: "Papua Guinea e Re",
  PH: "Filipinet",
  PK: "Pakistani",
  PL: "Polanda",
  PM: "Saint Pierre dhe Miquelon",
  PN: "Ishujt Pitkairn",
  PR: "Porto Riko",
  PS: "Palestina",
  PT: "Portugalia",
  PW: "Palau",
  PY: "Paraguaji",
  QA: "Katar",
  RE: "Reunioni",
  RO: "Romania",
  RS: "Serbia",
  RU: "Rusia",
  RW: "Ruanda",
  SA: "Arabia Saudite",
  SB: "Ishujt Solomon",
  SC: "Sejshellet",
  SD: "Sudani",
  SS: "Sudani Jugor",
  SE: "Suedia",
  SG: "Singapuri",
  SH: "Shën Helena",
  SI: "Sllovenia",
  SJ: "Svalbard dhe Jan Mayen",
  SK: "Sllovakia",
  SL: "Siera Leone",
  SM: "San Marino",
  SN: "Senegali",
  SO: "Somalia",
  SR: "Surinami",
  ST: "São Tomé dhe Príncipe",
  SV: "El Salvadori",
  SY: "Siria",
  SZ: "Svazilendi",
  TC: "Ishujt Turks dhe Caicos",
  TD: "Çadi",
  TF: "Territoret Jugore Franceze",
  TG: "Togo",
  TH: "Tajlanda",
  TJ: "Taxhikistani",
  TK: "Tokelau",
  TL: "Timori Lindor",
  TM: "Turkmenistani",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turqia",
  TT: "Trinidad dhe Tobago",
  TV: "Tuvalu",
  TW: "Tajvani",
  TZ: "Tanzania",
  UA: "Ukraina",
  UG: "Uganda",
  US: "United States",
  UY: "Uruguaji",
  UZ: "Uzbekistani",
  VA: "Vatikani",
  VC: "Saint Vincent dhe Grenadinet",
  VE: "Venezuela",
  VG: "Ishujt Virgjine Britanike",
  VI: "Ishujt Virgjine Amerikane",
  VN: "Vietnami",
  VU: "Vanuatu",
  WF: "Wallis dhe Futuna",
  WS: "Samoa",
  XK: "Kosova",
  YE: "Jemeni",
  YT: "Mayoti",
  ZA: "Afrika Jugore",
  ZM: "Zambia",
  ZW: "Zimbabve",
};
